version: '3.3'
services:
    adminer:
        image: adminer:latest
        ports:
            - 9081:8080
        networks:
            - auth0nestjs
    postgres:
        image: postgres:12
        volumes:
            - data-volume:/data/db
        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
        networks:
            - auth0nestjs
    redis:
        image: redis:latest
        volumes:
            - ./docker-data/redis:/data
        ports:
            - '6389:6379'
        networks:
            - auth0nestjs

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - auth0nestjs
networks:
    auth0nestjs:
volumes:
    data-volume:
    